"""v2 schema

Revision ID: 0170b87e7d08
Revises: 
Create Date: 2026-05-20 19:31:57.065077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0170b87e7d08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('primary_branch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_branch_id'], ['branches.id'], name='fk_projects_primary_branch', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_branch_id', sa.UUID(), nullable=True),
    sa.Column('created_from_beat_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('declared_arc', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("declared_arc IS NULL OR declared_arc IN ('rags_to_riches','riches_to_rags','man_in_hole','double_man_in_hole','icarus','cinderella','oedipus')", name='branch_declared_arc_check'),
    sa.CheckConstraint("state IN ('active','dormant','committed','graveyard')", name='branch_state_check'),
    sa.ForeignKeyConstraint(['created_from_beat_id'], ['beats.id'], name='fk_branches_fork_beat', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['parent_branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_created_from_beat_id'), 'branches', ['created_from_beat_id'], unique=False)
    op.create_index(op.f('ix_branches_parent_branch_id'), 'branches', ['parent_branch_id'], unique=False)
    op.create_index(op.f('ix_branches_project_id'), 'branches', ['project_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='character_status_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='setting_status_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_project_id'), 'settings', ['project_id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='theme_status_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_project_id'), 'themes', ['project_id'], unique=False)
    op.create_table('beats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('sequence_index_in_branch', sa.Integer(), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turning_point', sa.String(length=8), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('arousal', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='beat_status_check'),
    sa.CheckConstraint("turning_point IS NULL OR turning_point IN ('tp1','tp2','tp3','tp4','tp5')", name='beat_turning_point_check'),
    sa.CheckConstraint('(valence IS NULL) = (arousal IS NULL)', name='beat_affect_atomic'),
    sa.CheckConstraint('arousal IS NULL OR (arousal BETWEEN 0 AND 1)', name='beat_arousal_range'),
    sa.CheckConstraint('valence IS NULL OR (valence BETWEEN 0 AND 1)', name='beat_valence_range'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'sequence_index_in_branch', name='uq_beat_branch_position')
    )
    op.create_index(op.f('ix_beats_branch_id'), 'beats', ['branch_id'], unique=False)
    op.create_index(op.f('ix_beats_status'), 'beats', ['status'], unique=False)
    op.create_table('character_branch_overlays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('overlay_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='char_overlay_status_check'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'branch_id', name='uq_char_overlay_per_branch')
    )
    op.create_index(op.f('ix_character_branch_overlays_branch_id'), 'character_branch_overlays', ['branch_id'], unique=False)
    op.create_index(op.f('ix_character_branch_overlays_character_id'), 'character_branch_overlays', ['character_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('writer','assistant')", name='turn_role_check'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_branch_id'), 'conversation_turns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_created_at'), 'conversation_turns', ['created_at'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_beat_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('related_entity_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open','acknowledged','resolved')", name='issue_status_check'),
    sa.CheckConstraint("type IN ('contradiction','timeline_gap','character_inconsistency','world_rule_violation','pacing_anomaly','framework_misuse')", name='issue_type_check'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_branch_id'), 'issues', ['branch_id'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('setting_branch_overlays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setting_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('overlay_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='setting_overlay_status_check'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setting_id'], ['settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_id', 'branch_id', name='uq_setting_overlay_per_branch')
    )
    op.create_index(op.f('ix_setting_branch_overlays_branch_id'), 'setting_branch_overlays', ['branch_id'], unique=False)
    op.create_index(op.f('ix_setting_branch_overlays_setting_id'), 'setting_branch_overlays', ['setting_id'], unique=False)
    op.create_table('theme_branch_overlays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('overlay_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','committed','rejected')", name='theme_overlay_status_check'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'branch_id', name='uq_theme_overlay_per_branch')
    )
    op.create_index(op.f('ix_theme_branch_overlays_branch_id'), 'theme_branch_overlays', ['branch_id'], unique=False)
    op.create_index(op.f('ix_theme_branch_overlays_theme_id'), 'theme_branch_overlays', ['theme_id'], unique=False)
    op.create_table('beat_characters',
    sa.Column('beat_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beat_id', 'character_id')
    )
    op.create_index(op.f('ix_beat_characters_character_id'), 'beat_characters', ['character_id'], unique=False)
    op.create_table('beat_settings',
    sa.Column('beat_id', sa.UUID(), nullable=False),
    sa.Column('setting_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setting_id'], ['settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beat_id', 'setting_id')
    )
    op.create_index(op.f('ix_beat_settings_setting_id'), 'beat_settings', ['setting_id'], unique=False)
    op.create_table('beat_themes',
    sa.Column('beat_id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beat_id', 'theme_id')
    )
    op.create_index(op.f('ix_beat_themes_theme_id'), 'beat_themes', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beat_themes_theme_id'), table_name='beat_themes')
    op.drop_table('beat_themes')
    op.drop_index(op.f('ix_beat_settings_setting_id'), table_name='beat_settings')
    op.drop_table('beat_settings')
    op.drop_index(op.f('ix_beat_characters_character_id'), table_name='beat_characters')
    op.drop_table('beat_characters')
    op.drop_index(op.f('ix_theme_branch_overlays_theme_id'), table_name='theme_branch_overlays')
    op.drop_index(op.f('ix_theme_branch_overlays_branch_id'), table_name='theme_branch_overlays')
    op.drop_table('theme_branch_overlays')
    op.drop_index(op.f('ix_setting_branch_overlays_setting_id'), table_name='setting_branch_overlays')
    op.drop_index(op.f('ix_setting_branch_overlays_branch_id'), table_name='setting_branch_overlays')
    op.drop_table('setting_branch_overlays')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_branch_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_conversation_turns_created_at'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_branch_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_character_branch_overlays_character_id'), table_name='character_branch_overlays')
    op.drop_index(op.f('ix_character_branch_overlays_branch_id'), table_name='character_branch_overlays')
    op.drop_table('character_branch_overlays')
    op.drop_index(op.f('ix_beats_status'), table_name='beats')
    op.drop_index(op.f('ix_beats_branch_id'), table_name='beats')
    op.drop_table('beats')
    op.drop_index(op.f('ix_themes_project_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_settings_project_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_branches_project_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_parent_branch_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_created_from_beat_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
